### ISSUE TITLE
Community Tasks

### ISSUE THREAD

**Issue by emlaura** [openclimatefix/.github#57]
### Community Engagement: GitHub + Hugging Face Review Tasks

**_w/c 9 Sep_**

- [ ] openclimatefix/ocf-meta-repo#12
- [ ] Identify repos we want to encourage people to contribute to @emlaura @peterdudfield 
- [ ] Identify inactive repos or repos that aren’t as beneficial for external community @peterdudfield  @emlaura 
- [ ] Remove inactive repos from ocf-meta-repos @peterdudfield 
- [ ] Identify useful categorisations for external contributors and add to ocf-meta-repo @emlaura 
- [ ] Review new catergorisations for external contributors sent over by Emily @Sukh-P 
- [x] openclimatefix/ocf-meta-repo#10
- [ ] Draft a standardised READ ME template for OCF repos + send to Emily for review @devsjc 
- [ ] openclimatefix/ocf-meta-repo#8
- [x] Re order repos based on traffic light colour

Extras
- [ ] openclimatefix/ocf-meta-repo#7
- [ ] Add the traffic lights to the individual repos
