### ISSUE TITLE
Change workflows to be reusable

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/.github#6]
## Detailed Description
GitHub just released reusable workflows, in beta, https://docs.github.com/en/actions/learn-github-actions/reusing-workflows 

It seems like we can reduce a lot of duplication in our repos by moving workflows, especially the PyPi publishing one, linter, and most of the test workflows to here, and just calling them in those repos.

## Context
Currently, we have the exact same workflows copied and pasted to all of our new nowcasting repos, and if we want to make changes to one, we have to manually copy and past it to all the other ones to propagate the change. 

## ToDos
- [x] Add Linter workflow (see d6744adb0a5e33e8096ea8f97497e9477d4d941a)
- [x] Add Test workflow (`pytest` and `pydoctest`)
- [x] Add Release workflow (see https://github.com/openclimatefix/.github/issues/6#issuecomment-951754235)

**Comment by JackKelly** [comment]
Sounds like a great idea!  Thanks for letting us know about GitHub's new reusable workflows beta :)
